version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"       # Ubicaci√≥n del package.json
    schedule:
      interval: "weekly"  # Dependabot revisa dependencias semanalmente
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "security"
